#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
    #### script to modify boundary file to reflect boundary conditions#############
    sed -i '/physical/d' constant/polyMesh/boundary
    sed -i "/wall_/,/startFace/{s/patch/wall/}" constant/polyMesh/boundary
    sed -i "/top/,/startFace/{s/patch/symmetryPlane/}" constant/polyMesh/boundary
    sed -i "/front/,/startFace/{s/patch/cyclic/}" constant/polyMesh/boundary
    sed -i "/back/,/startFace/{s/patch/cyclic/}" constant/polyMesh/boundary
    sed -i -e '/front/,/}/{/startFace .*/a'"\\\tneighbourPatch  back;" -e '}' constant/polyMesh/boundary
    sed -i -e '/back/,/}/{/startFace .*/a'"\\\tneighbourPatch  front;" -e '}' constant/polyMesh/boundary
    sed -i -e '/cyclic/,/nFaces/{/type .*/a'"\\\tinGroups        1(cyclic);" -e '}' constant/polyMesh/boundary
    sed -i -e '/wall_/,/}/{/type .*/a'"\\\tinGroups        1(wall);" -e '}' constant/polyMesh/boundary
    #### script to modify boundary file to reflect boundary conditions#############
cp -r 0.orig 0
pimpleFoam> log.pimpleFoam
#------------------------------------------------------------------------------
